'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";

export default function TermsOfServicePage() {
    return (
        <div className="min-h-screen flex items-center justify-center bg-background p-4">
            <Card className="w-full max-w-3xl">
                <CardHeader>
                    <div className="flex items-center justify-between">
                        <div>
                            <CardTitle className="text-2xl">Terms of Service</CardTitle>
                            <CardDescription>Last updated: {new Date().toLocaleDateString()}</CardDescription>
                        </div>
                        <Button variant="ghost" size="icon" asChild>
                            <Link href="/register">
                                <ArrowLeft />
                            </Link>
                        </Button>
                    </div>
                </CardHeader>
                <CardContent>
                    <ScrollArea className="h-96 pr-4">
                        <div className="space-y-4 text-sm text-muted-foreground">
                            <h3 className="font-semibold text-foreground">1. Introduction</h3>
                            <p>Welcome to PredictPro! These terms and conditions outline the rules and regulations for the use of PredictPro's services. By accessing this website and using our services, we assume you accept these terms and conditions. Do not continue to use PredictPro if you do not agree to all of the terms and conditions stated on this page.</p>

                            <h3 className="font-semibold text-foreground">2. License to Use</h3>
                            <p>Unless otherwise stated, PredictPro and/or its licensors own the intellectual property rights for all material on PredictPro. All intellectual property rights are reserved. You may access this from PredictPro for your own personal use subjected to restrictions set in these terms and conditions.</p>
                            <p>You must not:</p>
                            <ul className="list-disc pl-5 space-y-1">
                                <li>Republish material from PredictPro</li>
                                <li>Sell, rent or sub-license material from PredictPro</li>
                                <li>Reproduce, duplicate or copy material from PredictPro</li>
                                <li>Redistribute content from PredictPro</li>
                            </ul>

                             <h3 className="font-semibold text-foreground">3. User Accounts</h3>
                            <p>You are responsible for safeguarding your account and you agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account. You must provide a valid 1xBet ID to use our prediction services.</p>

                            <h3 className="font-semibold text-foreground">4. Predictions and Disclaimer</h3>
                            <p>The predictions provided by PredictPro are generated by an artificial intelligence model and are based on statistical analysis. They are for informational and entertainment purposes only. We make NO GUARANTEE of accuracy, "guaranteed wins," "fixed matches," or "sure bets." You use our predictions at your own risk. PredictPro is not responsible for any financial losses incurred from using our predictions.</p>

                            <h3 className="font-semibold text-foreground">5. Limitation of Liability</h3>
                            <p>In no event shall PredictPro, nor any of its officers, directors and employees, be held liable for anything arising out of or in any way connected with your use of this website whether such liability is under contract. PredictPro, including its officers, directors and employees shall not be held liable for any indirect, consequential or special liability arising out of or in any way related to your use of this Website.</p>

                             <h3 className="font-semibold text-foreground">6. Suspension and Termination</h3>
                            <p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease.</p>
                        </div>
                    </ScrollArea>
                </CardContent>
            </Card>
        </div>
    );
}
